package com.adzannotif.presentation.theme

import androidx.compose.ui.graphics.Color

// Light Theme Palette (Clean Emerald & Soft Mint)
val md_theme_light_primary = Color(0xFF006C4C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6F5E8)
val md_theme_light_onPrimaryContainer = Color(0xFF002114)
val md_theme_light_secondary = Color(0xFF7A5900)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE089)
val md_theme_light_onSecondaryContainer = Color(0xFF261900)
val md_theme_light_background = Color(0xFFF6F9F7)
val md_theme_light_onBackground = Color(0xFF181D1A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF181D1A)
val md_theme_light_surfaceVariant = Color(0xFFE8F0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4944)
val md_theme_light_outline = Color(0xFF6F7974)
val md_theme_light_outlineVariant = Color(0xFFC0C9C3)

// Dark Theme Palette (Deep Obsidian & Mint Accent)
val md_theme_dark_primary = Color(0xFF88D6B7)
val md_theme_dark_onPrimary = Color(0xFF003829)
val md_theme_dark_primaryContainer = Color(0xFF00513C)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F2D2)
val md_theme_dark_secondary = Color(0xFFFAC248)
val md_theme_dark_onSecondary = Color(0xFF402D00)
val md_theme_dark_secondaryContainer = Color(0xFF5C4300)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE089)
val md_theme_dark_background = Color(0xFF0F1513)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF131B18)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF22302A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C3)
val md_theme_dark_outline = Color(0xFF89938E)
val md_theme_dark_outlineVariant = Color(0xFF3F4944)

// Sprint 2 — Astronomy Night Sky Palette
val AstronomyBackgroundDeep = Color(0xFF050A14)
val AstronomyBackgroundMid = Color(0xFF0B1525)
val AstronomySurface = Color(0xFF111D30)
val AstronomyStarWhite = Color(0xFFF0F4FF)
val AstronomyMoonGold = Color(0xFFFAC248)
val AstronomySunAmber = Color(0xFFFF9A3C)
val AstronomyGoldenHour = Color(0xFFFFB347)
val AstronomyBlueHour = Color(0xFF5B8FD4)
val AstronomyTwilightCivil = Color(0xFF7CA5E0)
val AstronomyTwilightNautical = Color(0xFF8EB5EF)
val AstronomyTwilightAstro = Color(0xFFAFC8F0)
val AstronomyConstellationLine = Color(0xFF8EB5EF)
val AstronomyHorizon = Color(0xFF2A4A2A)
